// pm2 ecosystem config for ai-monitor
// Usage: pm2 start deploy/ecosystem.config.js
// Or:    pm2 reload deploy/ecosystem.config.js

module.exports = {
  apps: [
    {
      // Master relay — replaces ai-monitor-relay + claude-relay (FiscalAI)
      // Manages ALL projects from relay/projects.json
      name:        'relay-master',
      script:      'relay/master.js',
      cwd:         '/var/www/html/vilarkptl.com/ai-monitor',
      exec_mode:   'fork',
      instances:   1,
      autorestart: true,
      watch:       false,
      max_memory_restart: '256M',
      error_file:  '/var/log/ai-monitor/relay-master-error.log',
      out_file:    '/var/log/ai-monitor/relay-master-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      // Claude chat bot — Telegram direct interface with tool use
      name:        'claude-chat-bot',
      script:      'relay/chat-agent.js',
      cwd:         '/var/www/html/vilarkptl.com/ai-monitor',
      exec_mode:   'fork',
      instances:   1,
      autorestart: true,
      watch:       false,
      max_memory_restart: '128M',
      error_file:  '/var/log/ai-monitor/claude-chat-error.log',
      out_file:    '/var/log/ai-monitor/claude-chat-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      // DeepSeek V3 code reviewer — polls git log every 5min
      name:        'code-reviewer',
      script:      'relay/code-reviewer.js',
      cwd:         '/var/www/html/vilarkptl.com/ai-monitor',
      exec_mode:   'fork',
      instances:   1,
      autorestart: true,
      watch:       false,
      max_memory_restart: '64M',
      error_file:  '/var/log/ai-monitor/code-reviewer-error.log',
      out_file:    '/var/log/ai-monitor/code-reviewer-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      // Cursor Cloud Agent self-hosted worker
      name:        'cursor-worker',
      script:      'relay/cursor-worker.js',
      cwd:         '/var/www/html/vilarkptl.com/ai-monitor',
      exec_mode:   'fork',
      instances:   1,
      autorestart: true,
      watch:       false,
      max_memory_restart: '128M',
      env_file:    '/var/www/html/vilarkptl.com/ai-monitor/relay/.env',
      error_file:  '/var/log/ai-monitor/cursor-worker-error.log',
      out_file:    '/var/log/ai-monitor/cursor-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },

    // ── Multi-account Claude proxies (1 Max + 4 Pro) ──────────────────────────
    // Each proxy runs claude CLI authenticated as a different account.
    // Setup: su - <user> -c "claude auth login" once per account.
    // Routing: relay/master.js selectProxy() routes by project/complexity.
    {
      // Max account — coordinator, fiscalai, fiscalai-front (complex/critical)
      name:        'claude-proxy-max',
      script:      'deploy/claude-proxy.js',
      args:        '--port 5001',
      cwd:         '/var/www/html/vilarkptl.com/ai-monitor',
      exec_mode:   'fork',
      instances:   1,
      autorestart: true,
      watch:       false,
      max_memory_restart: '128M',
      env: {
        CLAUDE_BIN:      '/usr/local/bin/claude',
        HOME:            '/root',
        CLAUDE_RUN_USER: 'german',
      },
      error_file: '/var/log/ai-monitor/claude-proxy-max-error.log',
      out_file:   '/var/log/ai-monitor/claude-proxy-max-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      // Pro account 1 — round-robin for standard projects
      name:        'claude-proxy-pro-1',
      script:      'deploy/claude-proxy.js',
      args:        '--port 5002',
      cwd:         '/var/www/html/vilarkptl.com/ai-monitor',
      exec_mode:   'fork',
      instances:   1,
      autorestart: true,
      watch:       false,
      max_memory_restart: '128M',
      env: {
        CLAUDE_BIN:      '/usr/local/bin/claude',
        HOME:            '/home/claudepro1',
        CLAUDE_RUN_USER: 'claudepro1',
      },
      error_file: '/var/log/ai-monitor/claude-proxy-pro1-error.log',
      out_file:   '/var/log/ai-monitor/claude-proxy-pro1-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      // Pro account 2
      name:        'claude-proxy-pro-2',
      script:      'deploy/claude-proxy.js',
      args:        '--port 5003',
      cwd:         '/var/www/html/vilarkptl.com/ai-monitor',
      exec_mode:   'fork',
      instances:   1,
      autorestart: true,
      watch:       false,
      max_memory_restart: '128M',
      env: {
        CLAUDE_BIN:      '/usr/local/bin/claude',
        HOME:            '/home/claudepro2',
        CLAUDE_RUN_USER: 'claudepro2',
      },
      error_file: '/var/log/ai-monitor/claude-proxy-pro2-error.log',
      out_file:   '/var/log/ai-monitor/claude-proxy-pro2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      // Pro account 3
      name:        'claude-proxy-pro-3',
      script:      'deploy/claude-proxy.js',
      args:        '--port 5004',
      cwd:         '/var/www/html/vilarkptl.com/ai-monitor',
      exec_mode:   'fork',
      instances:   1,
      autorestart: true,
      watch:       false,
      max_memory_restart: '128M',
      env: {
        CLAUDE_BIN:      '/usr/local/bin/claude',
        HOME:            '/home/claudepro3',
        CLAUDE_RUN_USER: 'claudepro3',
      },
      error_file: '/var/log/ai-monitor/claude-proxy-pro3-error.log',
      out_file:   '/var/log/ai-monitor/claude-proxy-pro3-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      // Pro account 4
      name:        'claude-proxy-pro-4',
      script:      'deploy/claude-proxy.js',
      args:        '--port 5005',
      cwd:         '/var/www/html/vilarkptl.com/ai-monitor',
      exec_mode:   'fork',
      instances:   1,
      autorestart: true,
      watch:       false,
      max_memory_restart: '128M',
      env: {
        CLAUDE_BIN:      '/usr/local/bin/claude',
        HOME:            '/home/claudepro4',
        CLAUDE_RUN_USER: 'claudepro4',
      },
      error_file: '/var/log/ai-monitor/claude-proxy-pro4-error.log',
      out_file:   '/var/log/ai-monitor/claude-proxy-pro4-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },

    // ── FinBot (ruta actualizada tras migración a repo propio) ─────────────────
    {
      name:        'conversation-engine',
      script:      'conversation_engine.py',
      interpreter: '/var/www/html/vilarkptl.com/ai-monitor/financial/bot/sims/mtproto/venv/bin/python',
      cwd:         '/var/www/html/vilarkptl.com/ai-monitor/financial/bot/sims/mtproto',
      exec_mode:   'fork',
      instances:   1,
      autorestart: true,
      watch:       false,
      max_memory_restart: '128M',
      env_file:    '/var/www/html/vilarkptl.com/ai-monitor/financial/.env',
      error_file:  '/root/.pm2/logs/conversation-engine-error.log',
      out_file:    '/root/.pm2/logs/conversation-engine-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      // financial-bot — migrated to own repo at /var/www/html/vilarkptl.com/financial-bot
      name:        'financial-bot',
      script:      'financial-bot.js',
      cwd:         '/var/www/html/vilarkptl.com/financial-bot',
      exec_mode:   'fork',
      instances:   1,
      autorestart: true,
      watch:       false,
      max_memory_restart: '256M',
      env_file:    '/var/www/html/vilarkptl.com/financial-bot/.env',
      error_file:  '/var/log/ai-monitor/financial-bot-error.log',
      out_file:    '/var/log/ai-monitor/financial-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name:        'ai-monitor',
      script:      'backend/server.js',
      cwd:         '/var/www/html/vilarkptl.com/ai-monitor',
      instances:   1,
      autorestart: true,
      watch:       false,
      exec_mode:   'fork',
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
        PORT:     3010,
        DB_HOST:  '127.0.0.1',
        DB_PORT:  3306,
        DB_USER:  'root',
        DB_NAME:  'ai_monitoring',
      },
      error_file:  '/var/log/ai-monitor/error.log',
      out_file:    '/var/log/ai-monitor/out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
